language: python


env:
    - CONDA="python=2.7"
    - CONDA="python=3.4"
    - CONDA="python=3.5"
    - CONDA="python=3.6"

before_install:
    - sudo apt-add-repository -y ppa:picaso/octave
    - sudo apt-get update -qq
    - sudo apt-get install -qq octave liboctave-dev
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    # Install numpy and scipy with conda for faster tests.
    - travis_retry conda create --yes -n test $CONDA pip numpy scipy
    - source activate test
    - travis_retry pip install -r requirements-dev.txt
    - conda info -a

script:
    - python setup.py test
